version: '2'

services:
  oasis-static:
    image: oasis/oasis-static
    container_name: oasis-static
    build:
      context: .
    ports:
      - "80:8080"
    environment:
      - VIRTUAL_HOST=nju.citicup.top
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=nju.citicup.top
      - LETSENCRYPT_EMAIL=1071956678@qq.com
#    networks:
#      - proxy
#networks:
#  proxy:
#    external: true
